name: orderxpress
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  easy_stepper: ^0.7.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  cool_stepper: ^1.2.1
  google_fonts: ^4.0.4
  map_location_picker: ^0.0.1
  intl_phone_field: ^3.2.0
  flutter_credit_card: ^3.0.7
  date_picker_plus: ^1.1.3
  location_picker_flutter_map: ^1.1.0
  map_picker_free: ^0.0.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  
